### PR TITLE
Allow Bundler 2.x and adjust to new travis env

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
@lzap I'd need a new gem release for this, as Ubuntu/focal is bringing Bundler 2.x

**Comment by lzap** [comment]
Sorry I have missed this one. Pushing out a new release.

**Comment by lzap** [comment]
Can you explain why you pinned bundler to 2.0?

**Comment by lzap** [comment]
Oh I can see it, we used to have 1.6 only, now it's 2.x using a different syntax we prefer in our gemspec.

**Comment by lzap** [comment]
Pushed 1.0.12.

**Pull request merged**
