### PR TITLE
Fixed build on FreeBSD

### PR DESCRIPTION
**Pull request by karli-sjoberg**
Confirmed this works, I successfully built it as a test. It´s a hack but it works for me™ :)

### CODE REVIEW

**Comment by sandfoxme** [comment]
Nice solution :D Sorry, no. This will break the build in Windows and MacOS

**Comment by sandfoxme** [comment]
I'm installing FreeBSD on a virtual machine now

**Comment by sandfoxme** [comment]
@karli-sjoberg hack was too dirty but the idea actually helped :)

**Comment by karli-sjoberg** [comment]
No problem! Beastie boys are here to help :)

/K

**Pull request closed without merging**
